FROM ubuntu:20.04
RUN apt-get update -y && apt-get install -y python3-pip python3-dev git gcc g++
RUN apt-get update -y && apt-get install -y dos2unix

COPY ../requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY .. /app

RUN dos2unix pipeline.sh && apt-get --purge remove -y dos2unix

RUN chmod +x pipeline.sh

ENTRYPOINT ["sh"]