model:
  get_data:
    file: 'data/raw/employee_attrition_train.csv'
  clean_data:
    missing_col: ['Age', 'DailyRate', 'DistanceFromHome']
    columns: ['EnvironmentSatisfaction', 'Attrition', 'Gender', 'JobInvolvement', 'JobLevel', 'JobSatisfaction',
               'MaritalStatus',
               'OverTime', 'PerformanceRating', 'RelationshipSatisfaction', 'WorkLifeBalance',
               'YearsSinceLastPromotion']
  split_data:
    test_size: 0.2
    random_state: 101
  train_model:
    max_depth: 50
    n_estimators: 200
    random_state: 101

rds: "data/raw/employee_results.csv"

s3: 's3://2022-msia423-yang-chenxin/raw_data/employee_train.csv'

local: 'data/raw/employee_attrition_train.csv'




